### ISSUE TITLE
sbnanalysis should participate in the regular build

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbncode#8] opened 2020-06-15 17:23 UTC
What is the motivation for sbnanalysis to need an independent build step to the rest of sbncode? Can it just be included in the main mrb build?

**Comment by wesketchum** [comment] 2020-10-16 18:17
I think this is duplicated by #7 . Going to label as duplicate, but once confirmed we should close.

**Comment by wesketchum** [comment] 2021-07-28 16:09
I'm closing this as a duplicate of #7

**Closed by wesketchum** 2021-07-28 16:09 UTC
Labels: duplicate
